name: Esto es una demo
on: [push]

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hola mundo"
        name: Hola mundo
      - name: Adios
        run: echo "Adios"
      - run: echo "..."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repositiry has "
      - run: echo "The worflow is now ready to test"
